[toolchain]
channel = "1.92.0"
profile = "minimal"
# See https://rust-lang.github.io/rustup/concepts/components.html
components = ["rustc", "cargo", "rustfmt", "rust-std", "rust-analyzer", "clippy", "rust-src"]
